# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David.Hu's Github Pages! 
email: 852192880@qq.com 
description: > # this means to ignore newlines until "baseurl:"
       David Hu's Github Pages!David Hu,is the guy who in favor of J2EE technology!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://divadoec.github.io/" # the base hostname & protocol for your site
twitter_username: DavidHu 
github_username:  divadoec 

# Build settings
markdown: kramdown
